add 1.24 release notes
okteto/docs pull request #818
Opened 2024-09-04 05:31 UTC by codyjlandstrom

2024-09-04 06:11 UTC, pchico83 requested changes

2024-09-04 06:11 UTC, pchico83 commented on src/content/release-notes.mdx
> +- Added tolerations for EventsExporter StatefulSet  <!-- 8446 -->
This is a feature, not an improvement. @jvc5546 Could you document the event exporter section in our helm values?

2024-09-04 06:11 UTC, pchico83 commented on src/content/release-notes.mdx
> +- Updated pipeline-runner image to v1.0.5 to update cue to 0.9.2 to fix vulnerabilities  <!-- 8482 -->
We never mention vulnerabilities, unless it's a patch release

2024-09-04 06:11 UTC, pchico83 commented on src/content/release-notes.mdx
> +### New Features
@codyjlandstrom we are adding support for buildkit bridge mode. @jLopezbarb could you create a separate PR to document it in the helm values? And explain the advantages of using bridge mode?

2024-09-04 06:11 UTC, pchico83 commented on src/content/release-notes.mdx
> +### Improvements
We always mention the upgrade to the Okteto CLI version. In this case, we are upgrading to CLI 2.31.0.
The main features are:
- Replace RSA by ECDSA for SSH keys. This allows the use of debuggers with Visual Studio with Development Containers
- Prevent syncthing to restart and activating [relay](https://docs.syncthing.net/users/relaying.html) if the synching configuration is lost

2024-09-04 06:11 UTC, pchico83 commented on src/content/release-notes.mdx
> +- Upgraded ingress-nginx to v4.11.2  <!-- 8460 -->
Let's add a link to the nginx release notes:
https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.11.2

2024-09-04 14:30 UTC, pchico83 commented on src/content/release-notes.mdx
> +### New Features
PR documenting buildkit network mode:
https://github.com/okteto/docs/pull/819

2024-09-04 14:38 UTC, pchico83 commented on src/content/release-notes.mdx
> +- Upgraded [ingress-nginx to v1.11.2](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.11.2)  <!-- 8460 -->
@codyjlandstrom the breaking change is a very uncommon case. I would explain more about it. Maybe something like "This `ingress-nginx` release comes with a breaking change only affecting edge case" And link to the issue where it's explained:
https://github.com/kubernetes/ingress-nginx/issues/11866
They didn't document it as a breaking change on their release notes

2024-09-05 05:51 UTC, pchico83 approved these changes

2024-09-05 06:02 UTC, codyjlandstrom commented on src/content/release-notes.mdx
> +- Enable [multi-user token authentication](self-hosted/install/auth/token.mdx)  <!-- https://github.com/okteto/app/pull/8481 -->
https://github.com/okteto/docs/pull/820

2024-09-05 06:12 UTC, pchico83 commented on src/content/release-notes.mdx
> +- Added tolerations for EventsExporter StatefulSet  <!-- 8446 -->
@codyjlandstrom added a PR to document the event exporter. I would link to the event exporter docs here:
https://github.com/okteto/docs/pull/821

2024-09-06 23:42 UTC, merged